Manager:
  experiment: OCT-Classification
  run: ResNetWide101
  save_point: /home/travail/clement/runs/
  gpu: [0,1,2, 3]
  max_saved_model: 1
  num_workers: 8 # Workers used for parallel data loading
  dist_backend: nccl
  seed: 1234

  tracking_uri: http://localhost:5010
  #tracking_uri: /usagers/clpla/Projects/runs/mlruns/
  artifact_uri: sftp://clement@m3202-10.demdgi.polymtl.ca/home/clement/Documents/Clement/runs/server/artifact/
  #artifact_uri:
  amp: True
  grad_scaling: True

Dataset:
#  shape: [1520,496] # wxh
  #shape: [224, 224]
  shape: [384, 384]
  keep_size_ratio: False
  img_url: /home/travail/clement/Kermany/CellData/OCT/train/
  recursive_loading: True
Test:
  img_url: /home/travail/clement/Kermany/CellData/OCT/test/

Preprocessing:
  #mean: [0.485, 0.456, 0.406]
  #std: [0.229, 0.224, 0.225]
  mean: [0.5,0.5,0.5]
  std: [0.5,0.5,0.5]
Validation:
  size: 500
  log_interval: 5000
  max_batch_validation: -1

Training:
  epochs: 50
  batch_size: 32
  iters_to_accumulate: 1
  #grad_clipping: 1.0



Loss:
  fusion: sum
  type: SoftCrossEntropy
  params_loss:
    SoftCrossEntropy:
      smooth_factor: 0.05

  weighted_loss: True
  params_weighting:
    mode: balanced
    log_smoothing: 1.5
    center_mean: 0

Optimizer:
  solver: SGD
  params_solver:
    lr: 0.001
#    betas: [.9,.99]
    weight_decay: 0.003
    nesterov: True
    momentum: 0.9
    dampening: 0

Learning_rate_scheduler:
  update_type: on_validation # or on_epoch
  scheduler: ReduceLROnPlateau
  params_scheduler:
    mode: max
    factor: 0.5
    patience: 10
    min_lr: 0.0000001
    verbose: True

Network:
  architecture: ResNet152
#  architecture: Wide ResNet-101-2
#  architecture: vit_base_patch32_384
  pretrained: True
  n_classes: 4
  synchronized_batch_norm: True

